# Frontend-only Docker Compose for local development
# This simulates Vercel's local environment

version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eduhub-frontend
    ports:
      - "5173:5173"
    volumes:
      # Mount source for hot reload
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./.env:/app/.env
      # Don't mount node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # These can be overridden by .env file
      - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN:-dev-1fx6yhxxi543ipno.us.auth0.com}
      - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID:-s05QngyZXEI3XNdirmJu0CscW1hNgaRD}
      - VITE_AUTH0_REDIRECT_URI=${VITE_AUTH0_REDIRECT_URI:-http://localhost:5173/callback}
      - VITE_AUTH0_AUDIENCE=${VITE_AUTH0_AUDIENCE:-http://localhost:8000}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge