services:
  # Web service for the FastAPI backend
  - type: web
    name: eduhub-api
    runtime: python
    pythonVersion: "3.11"
    buildCommand: pip install -e ".[dev]"
    startCommand: python -m uvicorn eduhub.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./eduhub.db  # Using SQLite for free tier
      - key: REDIS_URL
        value: redis://localhost:6379/0  # Will use in-memory cache instead
      - key: PLONE_URL
        value: http://localhost:8080/Plone  # Update for production
      - key: PLONE_USERNAME
        sync: false  # Set in Render dashboard
      - key: PLONE_PASSWORD
        sync: false  # Set in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: AUTH0_DOMAIN
        value: dev-1fx6yhxxi543ipno.us.auth0.com
      - key: AUTH0_API_AUDIENCE
        value: https://eduhub-api.example.com
      - key: AUTH0_ALGORITHMS
        value: RS256
      - key: AUTH0_ISSUER
        value: https://dev-1fx6yhxxi543ipno.us.auth0.com/
      - key: CORS_ORIGINS
        value: https://eduhub-frontend-six.vercel.app,http://localhost:5173
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 8000

# Note: Redis and PostgreSQL removed for free tier deployment
# Free tier databases are ephemeral and limited
# Using SQLite for database and in-memory cache instead
